### ISSUE TITLE
[Suggestion] TAIGA mod compatibility

### ISSUE THREAD

**Issue by drakray** [MinecraftModDevelopment/BaseMetals#1]
Hi, I'd like to know if you could make a new mod to bridge between BaseMetals ans TAIGA please, because as of now there is no way to hammer the ore, as they use new tier of hardness which are not supported.

Or, maybe add a parameter to custom recipe to manually specify a hammer tier, that should do the job, and maybe allow for some other compatibility.
ex: mod:crackhammer->mod:ore->X*basemetals:metal_powder

Or, a MineTweaker API, could also do it.(something like `api.basemetals.crackhammer.tier1.add(<output>*X, <input>);`)

As of now, using
`taiga:mythril_ore->8*basemetals:mithril_powder`
add the recipe in JEI, but because TAIGA add higher hardness(5 to 7 I think), there is no cack hammer strong enough

**Comment by dshadowwolf** [comment]
Work has started. Please be patient, there are some odd corners and a relatively new internal API is in play.

**Comment by dshadowwolf** [comment]
Code for this is now in place. There is no artwork for any materials from TAIGA and the stuff they make in BMe and the localizations need to be done as well.

However... It's been less than a year since this issue was opened, and it's now closed.

**Comment by drakray** [comment]
thank you very much, it will be very useful :D

**Comment by dshadowwolf** [comment]
@drakray No problem. This also expands options for some other things - there is a somewhat vague plan for a MineTweaker/CraftTweaker integration and thanks to the way some of the internals are done, this will expand available options there as well.
