### ISSUE TITLE
Suggested metals

### ISSUE THREAD

**Issue by sky0-1** [MinecraftModDevelopment/BaseMetals#10]
Enderium (an alloy of metal and ender pearls) is highly used in popular tech mods, especially where teleportation and 'wireless' tech is involved.
To encourage the use of Base Metals in these mods, please support Enderium.

If this would fit better in Modern Metals, let me know and I'll move the issue there.

**Comment by jriwanek** [comment]
Enderium, Lumium, Signalum and a few others will be going into Fantasy metals, it's not quite completed yet, but there's a repo for it on the org.
