### ISSUE TITLE
Possible new things

### ISSUE THREAD

**Issue by TheCodedOne** [MinecraftModDevelopment/BaseMetals#12]
Different things for each metal:

- Sheers (?)

- Buckets (?)

- Cauldron (?)

- Minecarts (?)

 (?) = Probably not the best of ideas

**Comment by darkhax** [comment]
Out of this list, I think the only ones which make sense are the anvils, sheers, and possibly buckets. The functionality of the others would be hard to do, as their functions are not so easily defined.

**Comment by jriwanek** [comment]
Shears are already in dev, flint & steel is a no (obvious by the name), but BMe does allow it to be made from steel, I could remove the flint + iron recipe I suppose, Anvils are generally not made from non ferrous metals, rails are usually steel or wood, as for the rest, maybe add some suggestions for differences and I'll consider them further.
