### ISSUE TITLE
Metal ingots missing oreDict entries

### ISSUE THREAD

**Issue by desht** [MinecraftModDevelopment/BaseMetals#13]
To reproduce (on MMD server, release 1.5.1):
- Smelt down some coppper ore in a TiCo smeltery
- Get copper blocks via the basin - the blocks are Base Metals copper blocks
- Get ingots from the blocks - also from Base Metals
- Try to craft an EnderIO capacitor - you can't

Holding down Ctrl over an ingot (Actually Additions feature) shows detailed data for the item, you can see there are no oreDict entries.

If you pull copper ingots from the smeltery via the casting table, you get Forestry ingots, and they do have an oreDict entry (and work for making capacitors).

**Comment by jriwanek** [comment]
Should be fixed in latest dev code, will check again however.

**Comment by jriwanek** [comment]
Not found recently
