### ISSUE TITLE
Zinc ore missing smelting recipe?

### ISSUE THREAD

**Issue by BrisingrAerowing** [MinecraftModDevelopment/BaseMetals#14]
Zinc ore cannot be smelted in a furnace, as there is no recipe for that. Is that intended? There is a zinc ingot, and smelting worked before, so I would think it isn't.

**Comment by jriwanek** [comment]
Which version are you using?

**Comment by BrisingrAerowing** [comment]
v2.4.0.11

I added recipes with CraftTweaker.

**Comment by jriwanek** [comment]
Fixed in dev
