### ISSUE TITLE
Ticking player on donning steel breastplate

### ISSUE THREAD

**Issue by Syndaryl** [MinecraftModDevelopment/BaseMetals#15]
http://pastebin.com/StMfz3NH

I've had this happen a few times now. When I reload the world the armor is on and I don't have ticking player problems again until (sometimes) if I take the armor off and on again. Only sometimes. :/

**Comment by jriwanek** [comment]
Weird, This was reported on dev too and should already be fixed.

**Comment by Syndaryl** [comment]
Reset my build environment completely, hasn't come back again. I'm blaming this on my environment getting desync'd.
