### ISSUE TITLE
Crash with Base Metals

### ISSUE THREAD

**Issue by DatrixTHLK** [MinecraftModDevelopment/BaseMetals#19]
https://gist.github.com/DatrixTHLK/3dc30c3ff7c0959612ecfd75112f4821

Minecraft 1.10.2
Forge 2094-2095
Base Metals v2.4.0.11

All I did was start up minecraft and this mod showed up as being E (Errored) in the crash log.

Referencing issue [#46](https://github.com/elix-x/Forever-Enough-Items/issues/46) on elix-x github issues page

**Comment by jriwanek** [comment]
net.minecraftforge.fml.common.MissingModsException: Mod orespawn (DrCyano's Ore Spawn Mod) requires [1.0.0]

You forgot to install Orespawn, get it at:

https://minecraft.curseforge.com/projects/mmd-orespawn

**Comment by DatrixTHLK** [comment]
Doh... will do
