### ISSUE TITLE
BaseMetals crashing

### ISSUE THREAD

**Issue by pandorrama** [MinecraftModDevelopment/BaseMetals#21]
BaseMetals is crashing by using it with the new forge version 1.10.2 - 12.18.1.2095

**Comment by jriwanek** [comment]
Crash report please

**Comment by pandorrama** [comment]
[crash-2016-10-06_15.37.57-client.txt](https://github.com/MinecraftModDevelopment/BaseMetals/files/513858/crash-2016-10-06_15.37.57-client.txt)

**Comment by pandorrama** [comment]
ups, i should have read your comments first. 
I was missing the orespawn mod....
Sorry  for that..... :(
