### ISSUE TITLE
[Suggestion] Add Tinkers Construct tool parts support

### ISSUE THREAD

**Issue by Biochao** [MinecraftModDevelopment/BaseMetals#22]
Here's how Immersive Engineering adds support for it's metals. https://github.com/BluSunrize/ImmersiveEngineering/blob/5c97c06bcbd0e175740a94f6319a9bc6bc194410/src/main/java/blusunrize/immersiveengineering/common/util/compat/TConstructHelper.java

**Comment by jriwanek** [comment]
Already in progress, but semi-stalled due to things not working right, thanks for the info however, it might get it un-stalled. (:

**Comment by jriwanek** [comment]
Now in latest dev, likely still needs tweaks.

**Comment by majix560** [comment]
Can I have a copy of that dev version?
It's not on curseforge...
