### ISSUE TITLE
JEI / Waila compatibility issues

### ISSUE THREAD

**Issue by mankra** [MinecraftModDevelopment/BaseMetals#24]
Forge version: 1.10.2-12.18.2.2120
Base Metals version: 2.4.0.11
JEI version: 3.13.2.360
Waila version: 1.7.0-B3

- All Base Metals doors are listed twice with the second ones having no texture in the JEI item list.
- There's also no access to the door recipes via JEI, but they can be crafted.
- The doors show no texture in the Waila tooltip.

**Comment by mankra** [comment]
The-Fireplace [fixed the JEI issue](https://github.com/The-Fireplace/Adobe-Blocks/issues/7), maybe he can help.

**Comment by mankra** [comment]
I worked around the issue by putting the textureless doors on the JEI blacklist.

**Comment by dshadowwolf** [comment]
Update of JEI interface in progress - NEI code and WAILA to follow.

**Comment by dshadowwolf** [comment]
WAILA integration is now being worked on.

At the moment the only thing I can think of that is needed is lever states.

**Comment by dshadowwolf** [comment]
WAILA integration is now being worked on.

At the moment the only thing I can think of that is needed is lever states.
(Basic code is done, Mod compiles with WAILA in place - startup test and functionality tests happening now)

**Comment by dshadowwolf** [comment]
@mankra Looked at what you linked to. All that is done there is an internal blacklisting - while we could certainly do that, there is another fix that will be going in place here.

**Comment by dshadowwolf** [comment]
Basic JEI and WAILA support is in place. The display issue is one that has a different solution according to @jriwanek - so this issue is closed with JEI and WAILA implemented
