### ISSUE TITLE
[Missing Textures] Basemetals 1.10.2 forge 215

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MinecraftModDevelopment/BaseMetals#34]
![2017-01-14_19 10 37](https://cloud.githubusercontent.com/assets/10351221/21959450/a0dc925e-da8d-11e6-9052-e14fe5381b4c.png)

**Comment by P3rf3ctXZer0** [comment]
![2017-01-14_19 19 06](https://cloud.githubusercontent.com/assets/10351221/21959490/841baa00-da8e-11e6-9eaa-9d662e15da48.png)
![2017-01-14_19 19 07](https://cloud.githubusercontent.com/assets/10351221/21959491/841d0c60-da8e-11e6-8bf1-6cbaee4d4f33.png)
![2017-01-14_19 19 07_2](https://cloud.githubusercontent.com/assets/10351221/21959492/841d20d8-da8e-11e6-826b-3d715ea197dc.png)
![2017-01-14_19 19 08](https://cloud.githubusercontent.com/assets/10351221/21959495/84212430-da8e-11e6-9cd8-c7e57de6d045.png)
![2017-01-14_19 19 09](https://cloud.githubusercontent.com/assets/10351221/21959494/842057e4-da8e-11e6-87f2-70c56e3c385c.png)
![2017-01-14_19 19 11](https://cloud.githubusercontent.com/assets/10351221/21959493/841fd1de-da8e-11e6-921d-09ad765e2812.png)
![2017-01-14_19 19 11_2](https://cloud.githubusercontent.com/assets/10351221/21959498/8428a8c2-da8e-11e6-86e5-24330bef0c6e.png)
![2017-01-14_19 19 13](https://cloud.githubusercontent.com/assets/10351221/21959497/84279ab8-da8e-11e6-9880-299fcd0645cd.png)
![2017-01-14_19 19 14](https://cloud.githubusercontent.com/assets/10351221/21959496/84278cda-da8e-11e6-84b0-560f087fd8af.png)
![2017-01-14_19 19 15](https://cloud.githubusercontent.com/assets/10351221/21959499/842b56ee-da8e-11e6-9560-da4537eab468.png)
![2017-01-14_19 19 15_2](https://cloud.githubusercontent.com/assets/10351221/21959500/842d026e-da8e-11e6-8982-c633f305c6fd.png)
![2017-01-14_19 19 16](https://cloud.githubusercontent.com/assets/10351221/21959501/842f3da4-da8e-11e6-9711-4ef897885319.png)
![2017-01-14_19 19 17](https://cloud.githubusercontent.com/assets/10351221/21959502/8431e0ae-da8e-11e6-9778-3979752fb2fe.png)
![2017-01-14_19 19 19](https://cloud.githubusercontent.com/assets/10351221/21959503/8432458a-da8e-11e6-9ae4-bf0113679abd.png)
![2017-01-14_19 19 20](https://cloud.githubusercontent.com/assets/10351221/21959504/84367ea2-da8e-11e6-8c08-fe3932aa9a7c.png)
![2017-01-14_19 19 21](https://cloud.githubusercontent.com/assets/10351221/21959506/8439eb8c-da8e-11e6-8f7d-0dd2507960e1.png)
![2017-01-14_19 19 22](https://cloud.githubusercontent.com/assets/10351221/21959505/8437e206-da8e-11e6-8929-0d57aa6cc2fb.png)

**Comment by jriwanek** [comment]
Already fixed in dev
