### ISSUE TITLE
Plated shields

### ISSUE THREAD

**Issue by jriwanek** [MinecraftModDevelopment/BaseMetals#54]
See: https://github.com/cyanobacterium/BaseMetals/issues/60

Note:
Maybe adding extra durability, maybe for repair (Report was written before additional shields were implemented)

**Comment by dshadowwolf** [comment]
Repair of shields with a plate of the same material in place.

**Comment by dshadowwolf** [comment]
Attempts to similarly make generic shield+plate of better material = new shield of plate material using the anvil is falling flat
