### ISSUE TITLE
Add other mod compatability

### ISSUE THREAD

**Issue by TheCodedOne** [MinecraftModDevelopment/BaseMetals#7]

**Comment by iLexiconn** [comment]
No, BaseMetals shouldn't add this. Only OreDict support should be added.

**Comment by TheCodedOne** [comment]
BaseMetals should be responsible for its custom alloys.

**Comment by iLexiconn** [comment]
Other mods should accept oredict items in their recipes

**Comment by TheCodedOne** [comment]
Other mods do, but when its an alloy that no other mod adds, Base Metals is responsible.

**Comment by iLexiconn** [comment]
No it's not

**Comment by jriwanek** [comment]
Base metals will provide compatiblity for all mods that make sense, current dev tip has stuff like enderio already there.
